### ISSUE TITLE
Jubbot announcements should reference tracks' clipped length

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/thejub.pub#234] opened 2016-06-02 17:50 UTC
Not their pre-clipped length

**Comment by aromatt** [comment] 2016-06-21 15:57
@jeskaeli is this a duplicate of #228?

**Comment by jeskaeli** [comment] 2016-06-21 17:52
@aromatt sure is...I don't know how that happened!

**Closed** 2016-06-21 18:02 UTC
Labels: backend, bug, chat-bot
